//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Exam_Course
    {
        public int Std_id { get; set; }
        public int crs_id { get; set; }
        public int ex_id { get; set; }
        public Nullable<int> Grade { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
